package github.snomfish.functionality.event;

public enum EventId {
    BEFORE_MOVE_EVENT,
    USER_BEFORE_MOVE_EVENT,
    TARGET_BEFORE_MOVE_EVENT,

    DAMAGE_MODIFIER_EVENT,
    USER_DAMAGE_MODIFIER_EVENT,
    TARGET_DAMAGE_MODIFIER_EVENT;
}
