package github.snomfish.functionality.event;

public enum EventId {
    BEFORE_MOVE_EVENT,
    ACCURACY_CHECK_EVENT,
    PRE_DEAL_FORMULA_DAMAGE_EVENT,
    PRE_DAMAGE_EVENT,
    POST_DAMAGE_EVENT,
    CLUTCH_EVENT,
    HEALTH_DRAIN_EVENT,
    ENERGY_DRAIN_EVENT,


    PRE_STAT_CHANGES_EFFECT_EVENT,
    USER_LOWERED_TARGET_STATS_EVENT,
    TARGET_LOWERED_USER_STATS_EVENT,
    

    USER_ITEM_CONSUMED_EVENT,
    TARGET_ITEM_CONSUMED_EVENT,
    USER_ITEM_REMOVED_EVENT,
    TARGET_ITEM_REMOVED_EVENT;
}
