package github.snomfish.functionality.event;

public enum EventId {
    BEFORE_MOVE,
    USER_BEFORE_MOVE,
    TARGET_BEFORE_MOVE,

    ACCURACY_CHECK,
    USER_ACCURACY_CHECK,
    TARGET_ACCURACY_CHECK,

    DAMAGE_MODIFIER,
    USER_DAMAGE_MODIFIER,
    TARGET_DAMAGE_MODIFIER,

    USER_ITEM_CONSUMED,
    TARGET_ITEM_CONSUMED,
    ITEM_CONUMED,

    USER_ITEM_REMOVED,
    TARGET_ITEM_REMOVED,
    ITEM_REMOVED;
}
